### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by PatrickScheich** [openoms/raspiblitz-extras#1]
During install of BTC-RPC-Explorer via 
`./config.scripts/bonus.btc-rpc-explorer.sh on` 
I got an Error...

>  error err.code.match is not a function

I attached the npm log at [https://termbin.com/jxak]

Did I miss any prerequisites?

**Comment by openoms** [comment]
My RaspiBlitz is on the same versions of NodeJS and NPM.
Will try to reproduce.
Is RTL working for you? Try either the build in version or the update from here.

**Comment by PatrickScheich** [comment]
It is a RaspiBlitz v1.3 (updated from a v1.2) RTL is installed and working

**Comment by openoms** [comment]
I got similar errors when running the script with sudo.

Make sure you are logged with the user `admin`
and try again:
`/home/admin/config.scripts/bonus.btc-rpc-explorer.sh on`

will clarify this in the readme

**Comment by PatrickScheich** [comment]
Thanks a bunch.
Omitting the 'sudo' does it. 

rare case when providing less does the job :)
