### ISSUE TITLE
Wrong fanshim configuration

### ISSUE THREAD

**Issue by got3nks** [openoms/raspiblitz-extras#2]
ExecStart=/root/fanshim-python/examples/automatic.py --on-threshold 55 --off-threshold 70 --delay 2 --brightness 255

Should be 

ExecStart=/root/fanshim-python/examples/automatic.py --on-threshold 70 --off-threshold 55 --delay 2 --brightness 255

**Comment by openoms** [comment]
Fixed, thanks!
