### ISSUE TITLE
Remove txid_limit from Electrs config

### ISSUE THREAD

**Issue by got3nks** [openoms/raspiblitz-extras#3]
In order to allow history for addresses with more than 100 txs, you have to add a line in /home/electrs/.electrs/config.toml, which should be safe for a local node not exposed to the public:

`txid_limit = 0`

Otherwise the BTC-RPC-Explorer will not show any history for such addresses.

**Comment by openoms** [comment]
thanks will look into this.
Do you have an example of such address at hand to test?

**Comment by got3nks** [comment]
Any address with over 100 txs will not work. You can try Andrea's 1andreas3batLhQa2FawWjeyjCqyBzypd

**Comment by openoms** [comment]
On what hardware did you test this setting? Do you know if it triggers a reindex of some sort in Electrs? 
On my Odroid HC1 + SSD Electrs is going 100% CPU for an hour now and BTC-RPC-Explorer does not show any transactions for individual addresses. Both BTC-RPC-Explorer and Electrs are otherwise functional.

**Comment by got3nks** [comment]
Pi4 4GB ram + 1TB ssd. It doesn't trigger anything it's just a limit change. The txindex=1 is required for BTC-RPC-Explorer already.

**Comment by openoms** [comment]
Maybe that address is a bit of an overkill with 2033 transactions.
This one: 1Fm3C6rFjA7Y2nAPs8nyzpzT2s2Z9kCUBv with 357 transactions worked after a couple of seconds.

It does not seem to affect stability when electrs is scanning high amount of transactions so could remove the limit.

**Comment by openoms** [comment]
The new changes fixing this issue are waiting to be merged to the RaspiBlitz 1.4. The instructions in repo are modified to help testing.
