### ISSUE TITLE
Use Zap or Zeus with Tor

### ISSUE THREAD

**Issue by bitcoinheiro** [openoms/raspiblitz-extras#5]
This is not working, I get the same errors for both ZAP and Zeus... What could this be?
Maybe I need to install additional dependencies? Some change to the sh file?

Running on raspiblitz 1.3 with all your extra shells added - including the 00mainmenu where I got to the ZAP over TOR and Zeus over TOR shells.

Attached image with error messages. At the end, no QR code is displayed.
Thanks!

![image](https://user-images.githubusercontent.com/50273260/70537782-b3c88380-1b69-11ea-9cc8-e798f9e75e15.png)

**Comment by openoms** [comment]
It seems some dependencies of lndconnect were not installed with Go.
You can reinstall Go manually with the instructions here: 
https://github.com/openoms/bitcoin-tutorials/blob/master/Zeus_to_RaspiBlitz_through_Tor.md#install-lndconnect

Will try to reproduce the error.

**Comment by bitcoinheiro** [comment]
got "lndconnect outside GOPATH" when trying to make...
![image](https://user-images.githubusercontent.com/50273260/70668344-03976f80-1c7c-11ea-8029-1ab694bdddab.png)

**Comment by bitcoinheiro** [comment]
ok, guess I fixed it. Just reinstalling GO - again - worked...
Had to do the whole process manually, the sh didn't worked for me - QR code was not readable (too much info for the small screen I guess)

**Comment by openoms** [comment]
The path does get messed up easily once there are entries in different places. Sometimes it is best to start with a clean installation as you have done.

**Comment by bitcoinheiro** [comment]
All cool now, working like a charm. Thanks for the guides!
